project:
  type: website
  output-dir: docs

website:
  title: "Sheena Taylor"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      

format:
  html:
    theme: lux
    toc: false
    css: styles.css




