project:
  type: website
  output-dir: docs

website:
  title: "Sheena Taylor"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: case-studies.qmd
        text: Case Studies
      - href: insights.qmd
        text: Insights
      - href: tools.qmd
        text: Tools
      - href: projects.qmd
        text: Portfolio
      - href: visualizations.qmd
        text: Visualizations
      

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    toc: false
    css: styles.css
    smooth-scroll: true




